name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy
      run:  aws s3 cp s3://contents.virtusasystems.com C:\Users\sophia_rebecca\OneDrive\Desktop\testing --recursive
#    #   run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
#    #   run: aws s3 cp dist s3://vcp-angular.virtusasystems.com/ --recursive



# # name: Upload a folder to S3

# # on:
# #   push:
# #     branches:
# #     - master

# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest
# #     steps:
# #     - uses: actions/checkout@master
    
# #     - name: Copy a folder to s3
# #       uses: prewk/s3-cp-action@v2
# #       with:
# #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
# #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# #         source: './something-local'
# #         dest: 's3://some-bucket/something-remote'
# #         flags: --recursive
        
        
# #         name: Download a file from S3

# on:
#   push:
#     branches:
#     - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
    
#     - name: Copy s3 data
#       uses: prewk/s3-cp-action@v2
#       with:
#         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
#     - name: Copy s3 data 
#       run:
#        aws s3 cp s3://contents.virtusasystems.com ./C:\Users\sophia_rebecca\OneDrive\Desktop\virtusa_1\s3test --recursive

#         source: 's3://contents.virtusasystems.com'
#         dest: './C:\Users\sophia_rebecca\OneDrive\Desktop\virtusa_1\'
#         flags: --recursive
#          aws s3 cp s3://WholeBucket LocalFolder --recursive

